config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'

  authenticated :user do
    root to: 'docs#index', as: 'authenticated_root'
  end

  root to: 'welcome#index'

  resources :docs

end

app/models/doc.rb
class Doc < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :docs

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

	before_action :find_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.where(user_id: current_user).order("created_at DESC")
	end

	def show
	end

	def new
		@doc = current_user.docs.build
	end

	def edit
	end

	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'edit'
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private

		def doc_params
			params.require(:doc).permit(:title, :content)
		end

		def find_doc
			@doc = Doc.find(params[:id])
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, 'Submit' , class: 'buttonfix' %>
<% end %>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
	<h1>Edit</h1>

	<%= render 'form' %>
	<%= link_to 'Cancel', @doc %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div class="clearfix" id="docs">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
          <a href="<%= (url_for [doc]) %>">
          <div class="doc">
            <p class="title">
              <%= doc.title %>
            </p>
            <p class="date">
              <%= time_ago_in_words(doc.created_at) %>
            </p>
            <p class="content">
              <%= truncate(doc.content, length:50) %>
            </p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Create Doc!</h2>
      <p>Start Creating Documents and Organizing your life!</p>
	   <%= link_to 'Create Doc', new_doc_path, :id => "button", :class => "buttonfix" %>
    <% end %>
  </div>
</div>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
	<h1>New</h1>

	<%= render 'form' %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h1 class="title">
      <%= @doc.title %>
    </h1>
    <p>
      <%= simple_format(@doc.content) %>
    </p>
    <%= link_to 'Edit', edit_doc_path(@doc), :class => "button" %>
    <%= link_to 'Delete', doc_path(@doc), method: :delete, data: {confirm: "Are you sure?" }, :class => "button" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileCabinet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<div class="header_inner">
			<%= link_to 'FileCabinet', root_path, :id => "logo" %>
			
			<nav>
				<% if user_signed_in? %>
					<%= link_to 'Create Doc', new_doc_path %>
					<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
				<% else %>
					<%= link_to 'Log In', new_user_session_path %>
				<% end %>
			</nav>
		</div>
			
	</header>

	 <p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>	
		
	 <%= yield %>


</body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>FileCabinet</h1>
    <p>Your life's Work!</p>
    <%= link_to "Sign Up", new_user_registration_path, :id =>"button", :class => "button" %>
  </div>
</div>
<div id="testimonial">
  <div class="wrapper">
    <p class="quote">"I keep all our important documents with FileCabinet."</p>
    <p class="name">- Random Person</p>
  </div>
</div>
<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Journal</h2>
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in euismod sapien. Nam varius enim quis nibh sollicitudin ultrices. Nullam orci nisi, molestie a dignissim quis, varius et eros. Nullam et mattis odio. Aliquam ultricies eu purus et vulputate. Sed sed nisl mauris. Donec convallis consectetur vehicula. 
      </div>
      <div class="callout">
        <h2>Notes</h2>
        Aliquam sagittis blandit nulla eget finibus. Proin quis facilisis arcu. Donec a ipsum eget tortor sollicitudin posuere. Donec ac orci tellus. Maecenas vel libero ex. In condimentum a mauris et luctus. Fusce sed faucibus justo. 
      </div>
      <div class="callout">
        <h2>Epic</h2>
        Nulla nulla augue, suscipit et euismod blandit, consectetur sit amet augue. Vestibulum at leo velit. Nullam imperdiet, purus in consectetur laoreet, metus est rhoncus sem, ut fermentum neque quam at risus. Sed in pulvinar turpis. Fusce congue leo in nibh venenatis blandit id nec nulla. Aliquam erat volutpat
      </div>
    </div>
  </div>
</div>
<div id="bottom_cta">
  <div class="wrapper">
    <h2>Store All Your Notes!</h2>
    <p>Be Different, Join the Elite!</p>
    <%= link_to "Start Here!!!", new_user_registration_path, :id =>"button", :class => "button" %>
  </div>
</div>
 <footer>
      <p>© Copyright. All Rights Reserved | by 
        <%= link_to 'Tahsin Rashad', "https://github.com/Tahsin716", :target => "_blank" %></p>
  </footer>